---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ["forwarded_port", {guest: 4440, host: 4441}]

provisioner:
  name: chef_solo
  attributes:
    citadel:
      access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>


platforms:
  - name: ubuntu-12.04
    driver_config:
      require_chef_omnibus: '11.10.4'
    run_list:
    - recipe[apt]

suites:
- name: simple
  attributes:
    postgres:
      live:
        slave: localhost
  run_list:
  - recipe[rundeck]
  - recipe[rundeck-sql_test::simple]
